# Generated by Django 3.0.3 on 2020-02-16 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booklist', '0003_auto_20200216_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='userbook',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
