# Generated by Django 3.0.3 on 2020-02-16 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0004_book_userbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='userbook',
            new_name='user',
        ),
    ]
