# Generated by Django 3.0.3 on 2020-02-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0008_auto_20200219_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavorite',
            name='tracking',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
