# Generated by Django 3.0.3 on 2020-02-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0009_userfavorite_tracking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
    ]
